controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

set_language:
    path: /language/{locale}
    controller: App\Controller\LanguageController::setLanguage